#!/usr/bin/env python3
"""Build NodeTreeDemo.urp as a *native PolyScope node tree*.

Unlike the other sample programs (whose .urp is a flat one-node wrapper around a
.script produced by ``urp_convert``), this program's source of truth is THIS
script: it drives :class:`urctl.urp_builder.UrpProgram` to emit the typed node
tree PolyScope itself produces. Open the result in PolyScope and you see real,
editable program nodes — Folder, MoveJ/Waypoint, If, Loop, Popup — not an
opaque "Script" line.

``make regen-urps`` runs this (any ``tests/fixtures/programs/*/build.py``) to refresh the .urp.
Run standalone:  python tests/fixtures/programs/NodeTreeDemo/build.py
"""

from __future__ import annotations

import sys
from pathlib import Path

# Make `urctl` importable when run straight from a checkout (e.g. via
# `make regen-urps`), where only this script's dir is on sys.path.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from urctl.urp_builder import UrpProgram, Waypoint  # noqa: E402

# Joint poses (radians) within the UR10e's comfortable working range. These are
# the same joint values used by the verified load tests, so they replay cleanly
# on URSim without calibration.
HOME = [-1.6007, -1.7271, -2.2030, -0.8080, 1.5951, -0.0310]
PICK = [-1.5986, -1.9017, -2.1595, -0.6769, 1.5952, -0.0289]
PLACE = [-1.8000, -1.7271, -2.2030, -0.8080, 1.5951, -0.0310]


def build() -> UrpProgram:
    p = UrpProgram("NodeTreeDemo", installation="NodeTreeDemo", directory="/programs/NodeTreeDemo")
    p.comment("Generated by urctl.urp_builder — edit build.py, not the .urp")

    # Helper functions live in one script node; the visible flow calls them by
    # name, so the operator reads "open_gripper()" not the I/O plumbing.
    p.script_file(
        "helpers",
        "def open_gripper():\n"
        "  set_standard_digital_out(0, False)\n"
        "  sleep(0.3)\n"
        "end\n"
        "def close_gripper():\n"
        "  set_standard_digital_out(0, True)\n"
        "  sleep(0.3)\n"
        "end\n",
    )

    with p.folder("Startup"):
        p.script_line("open_gripper()")
        p.movej(Waypoint("Home", q=HOME))

    # Run three pick/place cycles, but only pick when the part-present sensor
    # (digital_in[0]) is high — a normal, recognisable UR program shape.
    with p.loop(3):
        with p.if_digital_in(0, True):
            p.movej(Waypoint("AbovePick", q=PICK))
            p.script_line("close_gripper()")
            p.movej(Waypoint("AbovePlace", q=PLACE))
            p.script_line("open_gripper()")
            p.movej(Waypoint("BackHome", q=HOME))

    p.popup("NodeTreeDemo complete")
    return p


def main() -> None:
    out = Path(__file__).resolve().parent / "NodeTreeDemo.urp"
    build().save(out)
    print(f"wrote {out} ({out.stat().st_size} bytes gzipped)")


if __name__ == "__main__":
    main()
